project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
"preserve_hierarchy": true
files:
- source: "/docs/**/*.en.*"
  translation: "/docs/**/%file_name%.%locale_with_underscore%.%file_extension%"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
- source: "/theme/overrides/*.en.html"
  translation: "/theme/overrides/%file_name%.%locale_with_underscore%.html"
  translation_replace:
    "en.": ""
  update_option: update_as_unapproved
